allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@effect/cli@0.75.2"
  - "@effect/cluster@0.59.0"
  - "@effect/platform-node-shared@0.60.0"
  - "@effect/platform-node@0.107.0"
  - "@effect/workflow@0.18.2"
